#!/usr/bin/env python3
"""
直接从模型预测并保存分割后的点云
一步到位，格式和raw目录一样

Usage:
    python tools/save_segmented_ply.py \
        configs/myplants.yaml \
        /path/to/checkpoint.pth \
        --output-dir ./output/segmented_ply
"""

import argparse
import os
import os.path as osp
import gorilla
import torch
import numpy as np
from tqdm import tqdm

from spformer.dataset import build_dataloader, build_dataset
from spformer.model import SPFormer
from spformer.utils import get_root_logger, rle_decode


def write_ply_with_normals(points, output_file, normals=None):
    """Write point cloud to PLY file with normals (matching raw format)"""
    if normals is None:
        normals = np.zeros_like(points)

    with open(output_file, 'w') as f:
        f.write('ply\n')
        f.write('format ascii 1.0\n')
        f.write('comment VCGLIB generated\n')
        f.write('obj_info Generated by SPFormer!\n')
        f.write('element vertex {:d}\n'.format(len(points)))
        f.write('property float x\n')
        f.write('property float y\n')
        f.write('property float z\n')
        f.write('property float nx\n')
        f.write('property float ny\n')
        f.write('property float nz\n')
        f.write('end_header\n')
        for point, normal in zip(points, normals):
            f.write('{:.6f} {:.6f} {:.6f} {:.6f} {:.6f} {:.6f}\n'.format(
                point[0], point[1], point[2],
                normal[0], normal[1], normal[2]))


def save_scan_as_ply(scan_id, coords, pred_instances, output_dir, class_names):
    """
    Save one scan's segmentation results as PLY files

    Format (same as raw):
      - stem.ply: all stem points
      - leaf_XXX_1.ply: individual leaf instances
      - error.ply: undetected points
    """
    # Create output directory for this scan
    scan_output_dir = osp.join(output_dir, scan_id)
    os.makedirs(scan_output_dir, exist_ok=True)

    # Convert coordinates to numpy
    if torch.is_tensor(coords):
        coords = coords.cpu().numpy()
    coords = coords.astype(np.float32)
    num_points = coords.shape[0]

    # Track which points have been assigned
    assigned_points = np.zeros(num_points, dtype=bool)

    # Separate predictions by class
    stem_points = []
    leaf_instances = []

    for instance in pred_instances:
        label_id = instance['label_id']
        score = instance['conf']
        mask = instance['pred_mask']

        # Skip low confidence predictions
        if score < 0.1:
            continue

        # Decode RLE mask if needed
        if isinstance(mask, dict):
            mask = rle_decode(mask)

        # Convert mask to numpy
        if torch.is_tensor(mask):
            mask = mask.cpu().numpy()

        # Ensure mask is boolean
        if mask.dtype != bool:
            mask = mask.astype(bool)

        # Get points for this instance
        if mask.sum() == 0:
            continue

        points = coords[mask]
        assigned_points[mask] = True

        # class_names: ['stem', 'leaf']
        # label_id: 1=stem, 2=leaf
        if label_id == 1:  # stem
            stem_points.append(points)
        elif label_id == 2:  # leaf
            leaf_instances.append(points)

    # Save stem points (combine all stem predictions)
    if len(stem_points) > 0:
        all_stem_points = np.vstack(stem_points)
        stem_file = osp.join(scan_output_dir, 'stem.ply')
        write_ply_with_normals(all_stem_points, stem_file)
        print(f"    Saved stem.ply: {all_stem_points.shape[0]} points")
    else:
        print(f"    No stem detected")

    # Save leaf instances (each leaf as separate file)
    if len(leaf_instances) > 0:
        # Sort by size (largest first)
        leaf_instances.sort(key=lambda x: len(x), reverse=True)

        for idx, leaf_points in enumerate(leaf_instances, start=1):
            leaf_file = osp.join(scan_output_dir, f'leaf_{idx:03d}_1.ply')
            write_ply_with_normals(leaf_points, leaf_file)
            print(f"    Saved leaf_{idx:03d}_1.ply: {leaf_points.shape[0]} points")
    else:
        print(f"    No leaves detected")

    # Save undetected points (error.ply)
    undetected_mask = ~assigned_points
    if np.any(undetected_mask):
        error_points = coords[undetected_mask]
        error_file = osp.join(scan_output_dir, 'error.ply')
        write_ply_with_normals(error_points, error_file)
        print(f"    Saved error.ply: {error_points.shape[0]} undetected points")
    else:
        print(f"    All points detected!")


def main():
    parser = argparse.ArgumentParser(description='直接预测并保存分割后的点云')
    parser.add_argument('config', type=str, help='配置文件路径')
    parser.add_argument('checkpoint', type=str, help='模型权重路径')
    parser.add_argument('--output-dir', type=str, required=True,
                       help='输出目录')
    parser.add_argument('--data-split', type=str, default='test',
                       choices=['train', 'val', 'test'],
                       help='数据集划分 (default: test)')
    args = parser.parse_args()

    # Load config
    cfg = gorilla.Config.fromfile(args.config)
    gorilla.set_random_seed(cfg.test.seed)
    logger = get_root_logger()

    # Load model
    logger.info(f'加载模型: {args.checkpoint}')
    model = SPFormer(**cfg.model).cuda()
    gorilla.load_checkpoint(model, args.checkpoint, strict=False)

    # Load dataset
    if args.data_split == 'test':
        dataset = build_dataset(cfg.data.test, logger)
        dataloader = build_dataloader(dataset, training=False, **cfg.dataloader.test)
    elif args.data_split == 'val':
        dataset = build_dataset(cfg.data.val, logger)
        dataloader = build_dataloader(dataset, training=False, **cfg.dataloader.val)
    else:  # train
        dataset = build_dataset(cfg.data.train, logger)
        dataloader = build_dataloader(dataset, training=False, **cfg.dataloader.train)

    # Class names
    class_names = dataset.CLASSES
    logger.info(f'类别: {class_names}')
    logger.info(f'数据集: {args.data_split}, 样本数: {len(dataset)}')

    # Create output directory
    os.makedirs(args.output_dir, exist_ok=True)
    logger.info(f'输出目录: {args.output_dir}')

    # Run prediction and save
    logger.info('开始预测并保存点云...')
    model.eval()

    with torch.no_grad():
        for batch in tqdm(dataloader, desc='Processing'):
            result = model(batch, mode='predict')

            scan_id = result['scan_id']
            pred_instances = result['pred_instances']

            # Load original coordinates from .pth file
            data_file = osp.join(
                cfg.data[args.data_split].data_root,
                args.data_split,
                f'{scan_id}.pth'
            )

            data = torch.load(data_file)
            if len(data) == 5:
                coords, _, _, _, _ = data
            else:
                coords, _, _ = data

            # Convert to numpy
            if torch.is_tensor(coords):
                coords = coords.cpu().numpy()
            coords = coords.astype(np.float32)

            print(f"  处理 {scan_id}:")
            print(f"    检测到 {len(pred_instances)} 个实例")

            # Save this scan
            save_scan_as_ply(
                scan_id, coords, pred_instances,
                args.output_dir, class_names)

    logger.info(f'\n✅ 完成！点云已保存到: {args.output_dir}')
    logger.info(f'\n输出结构:')
    logger.info(f'  {args.output_dir}/')
    logger.info(f'    <scan_id>/')
    logger.info(f'      stem.ply          - 所有茎的点')
    logger.info(f'      leaf_001_1.ply    - 叶子实例1')
    logger.info(f'      leaf_002_1.ply    - 叶子实例2')
    logger.info(f'      ...')
    logger.info(f'      error.ply         - 未检测到的点')


if __name__ == '__main__':
    main()
